---
title: |
  "Assessing the quality of groundfish population indices derived from the Small-mesh Multi-species Bottom Trawl Survey"
french_title: Titre ici (*Nom latin de l'espèce*)
year: 2025
report_number: 3667
author: |
  Jillian C. Dunic and
  Sean C. Anderson
author_list: "Dunic, J.C. and Anderson, S.C."
region: Pacific Region
french_region: Région du Pacifique
isbn: "978-0-660-75374-4"
report_DOI: "10.60825/rjyz-8w29"
address: |
  Pacific Biological Station\
  Fisheries and Oceans Canada, 3190 Hammond Bay Road\
  Nanaimo, British Columbia, V9T 6N7, Canada\
french_address: |
  Station biologique du Pacifique\
  Pêches et Océans Canada, 3190 Hammond Bay Road\
  Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  \smallskip
phone: "(555) 555-5555"
author_footnote: "Email: First.Author@dfo-mpo.gc.ca | telephone: (250) 756-5555"
abstract: |
  Since 1973, Fisheries and Oceans Canada has conducted the Small-mesh Multi-species Bottom Trawl Survey (SMMS), the longest continuous fisheries-independent monitoring time series for groundfish off the west coast of Vancouver Island (WCVI). Initially designed to assess Pink shrimp (*Pandalus jordani*) populations, the survey also samples groundfish. The SMMS provides a valuable historical baseline for groundfish species, as current groundfish trawl surveys began in 2003 and are biennial across regions. However, changes to the SMMS, including changes to the sampling area, fishing gear, and catch recording procedures, may affect the quality of groundfish population indices. Here, we summarise these changes and examine their impact on relative biomass indices for groundfish. We compare spatiotemporal model-based population indices from the SMMS with other regional indices and examine the distribution of lengths and ages in comparison to the synoptic West Coast Vancouver Island trawl survey (SYN WCVI). Our analysis suggests that the modelled SMMS index is likely an appropriate index of relative biomass for many groundfish species. However, changes to the survey, such as the switch to comprehensive species sorting and identification, introduce uncertainties in the pre-2003 data. Additionally, the SMMS detected signs of rockfish recruitment earlier than the SYN WCVI for some species.

french_abstract: |
  Depuis 1973, Pêches et Océans Canada effectue le relevé au chalut de fond multispécifique à petites mailles (SMMS), la plus longue série chronologique continue de surveillance indépendante des pêches pour les poissons de fond au large de la côte ouest de l'île de Vancouver (WCVI). Conçue à l'origine pour évaluer les populations de crevettes roses (*Pandalus jordani*), l'étude échantillonne également les poissons de fond. Le SMMS fournit une base historique précieuse pour les espèces de poissons de fond, étant donné que les campagnes actuelles de chalutage des poissons de fond ont commencé en 2003 et sont biennales dans toutes les régions. Cependant, les changements apportés au SMMS, notamment en ce qui concerne la zone d'échantillonnage, les engins de pêche et les procédures d'enregistrement des captures, peuvent avoir une incidence sur la qualité des indices de population des poissons de fond. Nous résumons ici ces changements et examinons leur impact sur les indices de biomasse relative des poissons de fond. Nous comparons les indices de population spatio-temporels basés sur le modèle du SMMS avec d'autres indices régionaux et examinons la distribution des longueurs et des âges par rapport à l'étude synoptique au chalut de la côte ouest de l'île de Vancouver (SYN WCVI). Notre analyse suggère que l'indice SMMS modélisé est probablement un indice approprié de la biomasse relative pour de nombreuses espèces de poissons de fond. Cependant, les changements apportés à l'enquête, tels que le passage à un tri et à une identification complets des espèces, introduisent des incertitudes dans les données antérieures à 2003. En outre, le SMMS a détecté des signes de recrutement de sébastes plus tôt que le SYN WCVI pour certaines espèces.
citation_french: ""
output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: true
   line_nums: false
   line_nums_mod: 1
   lot_lof: false
   draft_watermark: false
type:
  techreport
knit: (function(input, ...) {
       csasdown::render()
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: [bib/mssm.bib]
header-includes:
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{makecell}

---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  autodep = TRUE,
  cache = FALSE, # !!
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
library(gfsynopsis)
```

```{r globals, cache=FALSE}
french <- TRUE
```
